const DeliveryOrders = [
  {
    id: 1,
    productName: "Heirloom Tomato",
    price: 5.99,
    quantity: 3,
    createdAt: "2024-07-19",
    customer: "John Doe",
    total: 27.44,
    Address: "Piassa",
    status: "Pending",
  },
  {
    id: 2,
    productName: "Organic Ginger",
    price: 6.5,
    quantity: 2,
    createdAt: "2024-07-20",
    customer: "Jane Smith",
    total: 15.99,
    Address: "Piassa",
    status: "Delivered",
  },
  {
    id: 3,
    productName: "Organic Ginger",
    price: 6.5,
    quantity: 2,
    createdAt: "2024-07-21",
    customer: "Alice Johnson",
    total: 33.43,
    Address: "Piassa",
    status: "Pending",
  },
];
export { DeliveryOrders };
